local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node

ls.add_snippets("python", {
	s("temppy", {
		t({
			"# from collections import Counter",
			"# from math import gcd, lcm",
			"# from bisect import bisect_left, bisect_right",
			"# from time import time",
			"",
			"",
			"MOD = 1e9 + 7",
			"",
			"",
			"def prime_factors(n):",
			"    factors = []",
			"    while n % 2 == 0:",
			"        factors.append(2)",
			"        n //= 2",
			"    i = 3",
			"    while i * i <= n:",
			"        while n % i == 0:",
			"            factors.append(i)",
			"            n //= i",
			"        i += 2",
			"    if n > 2:",
			"        factors.append(n)",
			"    return factors",
			"",
			"",
			"def fast_power(a, b):",
			"    res = 1",
			"    while b:",
			"        if b & 1:",
			"            res *= a % MOD",
			"        a *= a % MOD",
			"        b >>= 1",
			"    return res",
			"",
			"# xor_val = [0]*int((3*pow(10,5)+1))",
			"# for p in range(1, int((3*pow(10,5)+1))):",
			"#     xor_val[p] = xor_val[p - 1] ^ p",
			"# prefix sum",
			"# for i in range(1, n):",
			"#     a[i] += a[i - 1]",
			"",
			"",
			"def solve():",
			"    pass",
			"",
			"",
			"if __name__ == '__main__':",
			"    # start = time()",
			"    t = 1",
			"    # t = int(input())",
			"    for _ in range(t):",
			"        solve()",
			"    # end = time()",
			"    # print(end - start)",
		}),
	}),
})
